### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GSzabados**
pip to pip3 and I believe the commit number is not necessary anymore.

### CODE REVIEW

**Comment by rgerganov** [comment]
Thank you for this fix. I agree about `pip3` but let's keep the commit hash. I want to be sure that `CoAPthon3` won't break our program if they commit something wrong in the master branch.

**Comment by GSzabados** [comment]
Try to install it with the command containing the commit. I saw a message in the console meanwhile installing, that it cannot find commit, so assumes master. (Or something similar.)

**Comment by rgerganov** [comment]
It says "Did not find branch or tag '89d5173', assuming revision or ref." which is fine.

**Comment by rgerganov** [comment]
I have updated your patch and merged it, thanks!

**Pull request closed without merging**
